# head
author: 'bitblog.github.io'
title: 'bitblog.github.io'
keywords: 'битблог, bitblog, биткойн блог, bitcoin блог, блог о заработке биткойн, блог о bitcoin заработке, блог о криптовалюте, блог биткойн экспериментатора, блог биткойн энтузиаста, биткойн заработок с нуля'
description: 'Блог о том, как обычный парень экспериментирует'

baseurl: ""
url: "https://bitblog.github.io/"
permalink: /:categories/:title/

timezone: Europe/Moscow
